/**
 * QueryPlanValidator
 *
 * Validates LLM-generated Query Plans against the actual dataset schema,
 * verifying column existence, data type compatibility, operation validity,
 * and visualization rules. Prevents raw LLM hallucinated output from reaching execution.
 */
class QueryPlanValidator {
  /**
   * Validate and sanitize a Query Plan.
   * @param {Object} plan - Version 1.0 Query Plan object
   * @param {Object} semanticContext - Generated by DatasetSemanticContextBuilder
   * @returns {Object} { isValid: boolean, sanitizedPlan: Object, errors: Array<string>, confidence: number }
   */
  validate(plan, semanticContext) {
    const errors = [];
    const sanitizedPlan = JSON.parse(JSON.stringify(plan));
    let confidence = plan.confidence || 0.9;

    const allColumns = semanticContext.columns || [];
    const colNameMap = new Map(allColumns.map(c => [c.name.toLowerCase(), c]));

    // Helper: Find valid column by exact name or alias
    const resolveColumn = (targetName, preferredRoles = null) => {
      if (!targetName) return null;
      const lowerTarget = String(targetName).toLowerCase().trim();

      // 1. Direct case-insensitive match
      if (colNameMap.has(lowerTarget)) {
        return colNameMap.get(lowerTarget).name;
      }

      // 2. Alias matching
      for (const col of allColumns) {
        if (col.aliases && col.aliases.some(a => a.toLowerCase() === lowerTarget || lowerTarget.includes(a.toLowerCase()))) {
          if (!preferredRoles || preferredRoles.includes(col.semanticRole)) {
            return col.name;
          }
        }
      }

      // 3. Role-based fallback
      if (preferredRoles) {
        const matchingCol = allColumns.find(c => preferredRoles.includes(c.semanticRole));
        if (matchingCol) return matchingCol.name;
      }

      return null;
    };

    // 1. Validate & Sanitize Metric Column
    if (sanitizedPlan.metric?.column) {
      const validMetric = resolveColumn(
        sanitizedPlan.metric.column,
        ['monetary_metric', 'additive_metric', 'percentage_metric', 'ratio_metric', 'ordinal_metric', 'demographic_attribute']
      );

      if (validMetric) {
        sanitizedPlan.metric.column = validMetric;
      } else {
        const firstMeasure = semanticContext.measures[0];
        if (firstMeasure && sanitizedPlan.metric.aggregation !== 'count') {
          sanitizedPlan.metric.column = firstMeasure.name;
          confidence *= 0.8;
        } else {
          sanitizedPlan.metric.column = null;
        }
      }
    } else {
      // If aggregation is count or headcount is requested, leave metric.column as null for row frequency count
      if (sanitizedPlan.metric?.aggregation !== 'count' && sanitizedPlan.intent === 'overall_summary') {
        const firstMeasure = semanticContext.measures[0];
        if (firstMeasure) sanitizedPlan.metric.column = firstMeasure.name;
      } else {
        sanitizedPlan.metric.column = null;
      }
    }

    // 2. Validate & Sanitize Dimension Column
    if (sanitizedPlan.dimension?.column) {
      const validDim = resolveColumn(
        sanitizedPlan.dimension.column,
        ['categorical_dimension', 'geographic_dimension', 'status_dimension', 'ordinal_metric']
      );

      if (validDim) {
        sanitizedPlan.dimension.column = validDim;
      } else {
        const firstDim = semanticContext.dimensions[0];
        if (firstDim) {
          sanitizedPlan.dimension.column = firstDim.name;
          confidence *= 0.85;
        } else {
          sanitizedPlan.dimension.column = null;
        }
      }
    }

    // 3. Validate & Sanitize Temporal Column
    if (sanitizedPlan.temporal?.column || ['compare_periods', 'trend'].includes(sanitizedPlan.intent)) {
      const validDate = resolveColumn(
        sanitizedPlan.temporal?.column,
        ['temporal_dimension']
      ) || (semanticContext.temporalColumns[0] ? semanticContext.temporalColumns[0].name : null);

      if (validDate) {
        sanitizedPlan.temporal.column = validDate;
      } else if (['compare_periods', 'trend'].includes(sanitizedPlan.intent)) {
        errors.push('Temporal comparison requested but no valid date column exists in dataset.');
        confidence *= 0.5;
      }
    }

    // 4. Validate & Sanitize Filter Column
    if (sanitizedPlan.filter?.column) {
      const validFilterCol = resolveColumn(sanitizedPlan.filter.column);
      if (validFilterCol) {
        sanitizedPlan.filter.column = validFilterCol;
      } else {
        sanitizedPlan.filter.column = null;
        sanitizedPlan.filter.value = null;
      }
    }

    // 5. Enforce Visualization Compatibility Rules
    if (!sanitizedPlan.visualization) {
      sanitizedPlan.visualization = { type: 'bar' };
    }

    if (['compare_periods', 'trend'].includes(sanitizedPlan.intent)) {
      sanitizedPlan.visualization.type = 'line';
    } else if (['top_n', 'bottom_n', 'ranking', 'group_by'].includes(sanitizedPlan.intent)) {
      sanitizedPlan.visualization.type = 'bar';
    } else if (sanitizedPlan.intent === 'overall_summary') {
      sanitizedPlan.visualization.type = 'bar';
    }

    // 6. Enforce Limit Bounds
    sanitizedPlan.limit = typeof sanitizedPlan.limit === 'number'
      ? Math.min(Math.max(sanitizedPlan.limit, 1), 20)
      : 5;

    sanitizedPlan.confidence = Math.round(confidence * 100) / 100;

    return {
      isValid: errors.length === 0,
      sanitizedPlan,
      errors,
      confidence: sanitizedPlan.confidence
    };
  }
}

module.exports = new QueryPlanValidator();
