const llmService = require('../../llmService');

/**
 * AnswerGenerator
 *
 * Synthesizes clear, plain-English answers and executive key takeaways.
 * Enforces zero-hallucination rules: LLM relies strictly on deterministic math output.
 */
class AnswerGenerator {
  /**
   * Generates answer text and insights.
   * @param {Object} answerContext - Generated by ChatAnswerContextBuilder
   * @returns {Promise<{ answer: string, insights: Array<string> }>}
   */
  async generate(answerContext) {
    if (llmService.isAvailable()) {
      try {
        const llmResult = await this._generateWithLLM(answerContext);
        if (llmResult && llmResult.answer && Array.isArray(llmResult.insights)) {
          return llmResult;
        }
      } catch (err) {
        console.warn('[AnswerGenerator] LLM synthesis failed. Using rule fallback:', err.message);
      }
    }

    return this._generateWithRules(answerContext);
  }

  async _generateWithLLM(ctx) {
    const prompt = `You are a Senior Business Intelligence Analyst & Data Scientist.
You are answering a user question about a tabular dataset based strictly on verified calculations.

STRICT INSTRUCTIONS:
1. Use ONLY the verified mathematical result and evidence provided.
2. DO NOT recalculate, invent, or modify any numerical values.
3. Keep the "answer" field to a single direct, punchy plain-English sentence.
4. Provide 2 concise bullet points in "insights" highlighting key takeaways.
5. Output MUST be valid JSON only matching:
{
  "answer": "Direct plain-English sentence incorporating calculated metric values.",
  "insights": [
    "Key takeaway bullet 1.",
    "Key takeaway bullet 2."
  ]
}

USER QUESTION: "${ctx.question}"
VERIFIED COMPUTATIONAL EVIDENCE: ${JSON.stringify(ctx.evidence)}
EXECUTED ANALYSIS RESULT: ${JSON.stringify(ctx.analysisResult)}
METHODOLOGY: ${ctx.methodology}`;

    const raw = await llmService.generate(prompt);
    if (raw && raw.answer && Array.isArray(raw.insights)) {
      return raw;
    }
    return null;
  }

  _generateWithRules(ctx) {
    const { analysisResult, evidence } = ctx;
    const { action, result = [], metric, groupBy, targetVal, totalValue, avgValue, totalRows, dateFilter } = analysisResult;

    if (action === 'overall_summary') {
      const formattedValue = typeof targetVal === 'number' ? targetVal.toLocaleString('en-IN') : (totalValue?.toLocaleString('en-IN') || '0');
      const formattedAvg = typeof avgValue === 'number' ? avgValue.toLocaleString('en-IN') : '0';
      const metricLabel = (metric || 'Value').replace(/_/g, ' ');
      const scopeDesc = dateFilter ? `for ${dateFilter}` : `across ${totalRows || evidence.rowsMatched} dataset records`;

      return {
        answer: `Total ${metricLabel} ${scopeDesc} is ${formattedValue} (Average per record: ${formattedAvg}).`,
        insights: [
          `Total accumulated ${metricLabel} across ${totalRows || evidence.rowsMatched} active dataset rows reaches ${totalValue?.toLocaleString('en-IN') || formattedValue}.`,
          `Evaluated across ${totalRows || evidence.rowsMatched} dataset rows with minimum value ${result?.[2]?.Value || 0} and maximum value ${result?.[3]?.Value || 0}.`
        ]
      };
    }

    if (!result || result.length === 0) {
      return {
        answer: "No specific data points were found matching your criteria.",
        insights: ["Check if your dataset contains rows matching this query."]
      };
    }

    const topItem = result[0];
    const topName = topItem[groupBy] || topItem['Period'] || 'Top category';
    const topVal = topItem[metric || 'Value'] || topItem['Count'] || 0;
    const formattedVal = typeof topVal === 'number' ? topVal.toLocaleString('en-IN') : topVal;
    const metricLabel = (metric || 'Value').replace(/_/g, ' ');

    if (action === 'compare_periods') {
      const isDropQuery = /drop|fall|decline|decrease|why/i.test(ctx.question);
      let sharpestDrop = null;
      let minChange = 0;

      result.forEach((p, idx) => {
        if (p['Change %'] < minChange) {
          minChange = p['Change %'];
          sharpestDrop = { ...p, prev: result[idx - 1] };
        }
      });

      if (isDropQuery && sharpestDrop) {
        const dropPeriod = sharpestDrop.Period;
        const prevPeriod = sharpestDrop.prev ? sharpestDrop.prev.Period : 'prior period';
        const prevVal = sharpestDrop.prev ? sharpestDrop.prev[metric || 'Value'] : 0;
        const curVal = sharpestDrop[metric || 'Value'];

        return {
          answer: `${metricLabel} experienced its sharpest decline in ${dropPeriod}, dropping by ${Math.abs(minChange)}% compared to ${prevPeriod} (from ${prevVal.toLocaleString('en-IN')} to ${curVal.toLocaleString('en-IN')}).`,
          insights: [
            `Primary performance contraction occurred in ${dropPeriod} with a ${Math.abs(minChange)}% period-over-period fall.`,
            `Evaluated across all ${result.length} time periods in the uploaded dataset.`
          ]
        };
      }

      const lastItem = result[result.length - 1];
      const changePct = lastItem['Change %'] || 0;
      const isUp = changePct >= 0;

      return {
        answer: `Over time, ${metricLabel} reached ${lastItem[metric || 'Value']?.toLocaleString('en-IN')} in ${lastItem.Period} (${isUp ? '+' : ''}${changePct}% vs prior period).`,
        insights: [
          `Peak performance occurred in ${topName} with ${formattedVal} total ${metricLabel}.`,
          `Evaluated across ${result.length} distinct time periods in the dataset.`
        ]
      };
    }

    if (action === 'top_n') {
      return {
        answer: `${topName} leads as the top-ranked item with a total value of ${formattedVal}.`,
        insights: [
          `${topName} represents the highest contribution for ${metric || 'this metric'}.`,
          `Evaluated across the top ${result.length} performing segments in the dataset.`
        ]
      };
    }

    // Default group_by fallback
    const secondItem = result[1];
    let secondaryInsight = `Total across all ${result.length} categories analyzed.`;
    if (secondItem) {
      const secondName = secondItem[groupBy] || 'Runner up';
      const secondVal = secondItem[metric || 'Value'] || secondItem['Count'] || 0;
      const diffPct = topVal > 0 ? Math.round(((topVal - secondVal) / topVal) * 100) : 0;
      secondaryInsight = `${topName} generated ${diffPct}% more volume than ${secondName}.`;
    }

    return {
      answer: `${topName} is the best-performing ${groupBy || 'segment'} with total ${metricLabel} of ${formattedVal}.`,
      insights: [
        secondaryInsight,
        `${topName} leads all groups in the uploaded dataset.`
      ]
    };
  }
}

module.exports = new AnswerGenerator();
