/**
 * AnalyticalContextBuilder
 *
 * Exposes available analytical dimensions, metrics, time columns,
 * and valid aggregation operations for a given dataset semantic context.
 */
class AnalyticalContextBuilder {
  /**
   * Build analytical capabilities context.
   * @param {Object} semanticContext - Generated by DatasetSemanticContextBuilder
   * @returns {Object} Analytical Context payload
   */
  buildContext(semanticContext = {}) {
    const { columns = [], measures = [], dimensions = [], temporalColumns = [] } = semanticContext;

    const availableMetrics = measures.map(m => ({
      column: m.name,
      semanticRole: m.semanticRole,
      operations: m.aggregationCapabilities,
      min: m.statistics?.min,
      max: m.statistics?.max,
      mean: m.statistics?.mean
    }));

    const availableDimensions = dimensions.map(d => ({
      column: d.name,
      semanticRole: d.semanticRole,
      uniqueCount: d.uniqueCount,
      sampleValues: d.sampleValues
    }));

    const availableTemporal = temporalColumns.map(t => ({
      column: t.name,
      semanticRole: t.semanticRole,
      sampleValues: t.sampleValues
    }));

    // Detect pairwise relationships (e.g. valid dimension-measure pairs)
    const relationships = [];
    dimensions.forEach(d => {
      measures.forEach(m => {
        relationships.push({
          dimension: d.name,
          measure: m.name
        });
      });
    });

    return {
      availableMetrics,
      availableDimensions,
      temporalColumns: availableTemporal,
      relationships: relationships.slice(0, 15),
      supportedIntents: [
        'overall_summary',
        'aggregation',
        'group_by',
        'ranking',
        'top_n',
        'bottom_n',
        'comparison',
        'trend',
        'period_comparison',
        'growth',
        'distribution',
        'filtering'
      ]
    };
  }
}

module.exports = new AnalyticalContextBuilder();
